namespace TaskManager.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AutoGeneratedIDField : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.UserTasks");
            AlterColumn("dbo.UserTasks", "ID", c => c.Guid(nullable: false, identity: true));
            AddPrimaryKey("dbo.UserTasks", "ID");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.UserTasks");
            AlterColumn("dbo.UserTasks", "ID", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.UserTasks", "ID");
        }
    }
}
